services:
  app_demo:
    container_name: express_demo
    build:
      context: .
      dockerfile: Dockerfile
    command: ["node", "-r", "tsconfig-paths/register", "dist/app.js"]
    ports:
      - "6000:6000"
    env_file:
      - .env
    restart: always